// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hudson/HudsonChat.tsx": () => import("../components/mockups/hudson/HudsonChat.tsx"),
  "./components/mockups/hudson/HudsonDisruption.tsx": () => import("../components/mockups/hudson/HudsonDisruption.tsx"),
  "./components/mockups/hudson/HudsonItinerary.tsx": () => import("../components/mockups/hudson/HudsonItinerary.tsx")
};
